export const ActionType = {
  CHECK_LOGIN: `AUTH/CHECK_LOGIN`,
  GET_LOGIN: `AUTH/GET_LOGIN`,
  CHECK_REGISTER: `AUTH/CHECK_REGISTER`,
  CHECK_LOGOUT: `AUTH/CHECK_LOGOUT`,
  FETCH_LOGIN: `AUTH/FETCH_LOGIN`,
  FAILURE_LOGIN: `AUTH/FAILURE_LOGIN`,
  IS_AUTH: `AUTH/IS_AUTH`
};

// export const FETCH_LOGIN = `AUTH/FETCH_LOGIN`;
// export const FETCH_REGISTER = `AUTH/FETCH_REGISTER`;